# Generated by Django 4.2.1 on 2023-07-21 07:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noveltraveler',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='小说正文'),
        ),
    ]
