# Generated by Django 4.2.1 on 2023-07-21 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_alter_noveltraveler_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.noveltraveler', verbose_name='评论所属小说'),
        ),
        migrations.AddField(
            model_name='like',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.noveltraveler', verbose_name='赞所属小说'),
        ),
    ]
