# Generated by Django 4.2.1 on 2023-07-21 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fan', '0003_comment_novel_like_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='like',
            name='novel',
        ),
        migrations.CreateModel(
            name='LikeNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.noveltraveler', verbose_name='赞所属小说')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
        ),
        migrations.CreateModel(
            name='CommentNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='评论内容')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fan.noveltraveler', verbose_name='评论所属小说')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fan.userprofile')),
            ],
        ),
    ]
